### ISSUE TITLE
ImportError: cannot import name 'diversity_lib'

### ISSUE THREAD

**Issue by Congnguyenn** [sbslee/dokdo#57]
Dear @sbslee,
Thank you for your contribution, I have installed dokdo into Qiime2 (2020.2) but I encountered a problem related to the importing of "diversity_lib" module
I tried to upgrade the qiime2 to version 2020.8 as you suggested in the tutorial, but the problem still resist. Please take a look at the image below
![2023-11-21 17 57 16](https://github.com/sbslee/dokdo/assets/90585820/e2764934-2a21-4b4a-ba9c-7f01ac4d8a8c)

**Comment by sbslee** [comment]
Hi, please check #56 as I think it's related to your issue. Also, the version `2020.8` is very much old, please use the latest version. Finally, if the linked issue doesn't solve your problem, please provide the exact method or command line you used to install your QIIME 2.

**Comment by Congnguyenn** [comment]
Thank you, after updating the version of Qiime2 to 2022.8, the problem is gone.
